export const ON_SIZE_CHANGE = 'ON_SIZE_CHANGE';
export const ON_NAME_CHANGE = 'ON_NAME_CHANGE';
export const ON_GAME_ON = 'ON_GAME_ON';
export const ON_GAME_OFF = 'ON_GAME_OFF';
export const ADD_4_NEW_HIGHSCORE = 'ADD_4_NEW_HIGHSCORE';
export const ADD_6_NEW_HIGHSCORE = 'ADD_6_NEW_HIGHSCORE';
export const ADD_8_NEW_HIGHSCORE = 'ADD_8_NEW_HIGHSCORE';
